### ISSUE TITLE
libftdi1 dependency error

### ISSUE THREAD

**Issue by sandyjmacdonald** [pimoroni/propeller-hat#1]
Hey Phil. I get the following error when installing the Propeller IDE:

```
Selecting previously unselected package propelleride.
(Reading database ... 85351 files and directories currently installed.)
Unpacking propelleride (from propelleride-0.25.1-0-g5442b03-armhf.deb) ...
dpkg: dependency problems prevent configuration of propelleride:
 propelleride depends on libftdi1; however:
  Package libftdi1 is not installed.

dpkg: error processing propelleride (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils ...
Processing triggers for menu ...
Errors were encountered while processing:
 propelleride
```

Easily fixed with `sudo apt-get install libftdi1` and I reckon if you add it to the end of the `sudo apt-get install qt5-default qt5-qmake libegl1-mesa libgles2-mesa` [here](https://github.com/pimoroni/propeller-hat/blob/master/documentation/Propeller-IDE-Getting-Started.md#installing-pre-requisites) then it should all just work.

**Comment by Gadgetoid** [comment]
D'oh! Thank you! Good spot. I always miss these, despite multiple installations, since I often have libftdi1 preinstalled!
