### ISSUE TITLE
feature request: a C/C++ API lib for Raspbian 

### ISSUE THREAD

**Issue by shiftleftplusone** [pimoroni/propeller-hat#5]
feature request: 
a gcc/g++  C/C++ API lib for Raspbian would be very much appreciated!
(compatibility to pthread, wiringPi and pigpio necessary)

**Comment by Gadgetoid** [comment]
This is an interesting suggestion. Would you envision a "Firmata" style API where the C/C++ API controls the Propeller HAT via a pre-uploaded binary, or something else?

The Python SerialIO library contains a binary blob which it uploads to the Propeller before taking control, via serial, of its GPIO pins with a simple protocol. This could be replicated in C quite trivially.

**Comment by shiftleftplusone** [comment]
I don't know firmata,
something like the Arduino Sketch API commands would be nice
but either suggestions are appreciated, 
most of all: there will be simple C commands available!
