### ISSUE TITLE
Vncserver with Propeller

### ISSUE THREAD

**Issue by optimho** [pimoroni/propeller-hat#6]
I am using Jessie and connecting to the Raspberry with Vncserver and the keyboard is wrong.
The letters I type are not the ones that end up on the editor. This is not an issue with SimpleIDE or any other program I access with VncServer.

**Comment by Gadgetoid** [comment]
I came across this one before, and don't know if there's any way to fix it. I believe it's related to Qt plugins or something currently beyond my understanding. It might be worth filing an issue against the PropellerIDE project to see if anyone can help: https://github.com/parallaxinc/PropellerIDE/issues
