### ISSUE TITLE
serialio.py looking for missing "pins" module

### ISSUE THREAD

**Issue by rubergd** [pimoroni/propeller-hat#7]
Hi, I installed the p1 package and when I tried to test the serialio library using "sudo python -im p1.serialio", it complains about not being able to import the "pins" module.
I've done a bit of searching on the net and haven't been able to come up with anything as to where this module is supposed to come from.  It's not in the PIP list. Since pins.AsyncWorker() appears to be the main function behind reading the serial data from the Propeller Hat, i would appreciate it if you could tell me where I can locate it.  I am using Raspian Wheezy, Python 2.7, and GPIO, smbus, etc.  are installed. Thanks in advance!

**Comment by Gadgetoid** [comment]
This is a blunder on my part. "pins" is a badly named module that exists in the Explorer HAT library, and was intended to be a collection of useful patterns that could be used across libraries. It never quite made it to that state though!

I have in-lined the functions that p1.serialio requires from pins, so it should now work.

https://github.com/pimoroni/propeller-hat/commit/4d927cc1e3805e6fa793e66af93f727886c70475

**Comment by rubergd** [comment]
Beautiful!  Thanks for the response, Phillip.  It’s a handy little app.

..Don
